# Generated by Django 3.0.6 on 2020-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_production', models.IntegerField()),
                ('reported_production', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transport_trip', models.IntegerField()),
                ('dispatch', models.IntegerField()),
            ],
        ),
    ]
